import { createTheme } from "@material-ui/core";

export const theme = createTheme({
    palette: {
        primary: { main: "#39b03c", dark: "#208b3b", light: "#73c82a" },
        background: { default: "#f1fff2" },
        text: { primary: "#000000", secondary: "#ffffff" },
        secondary: { main: "#1a863c" },
        grey: { "100": "#44484d" },
    },
    shadows: [
        "none",
        "2px 10px 62px 0 rgb(0 0 0 / 83%)",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
        "none",
    ],
    typography: { h1: { color: "#44484d" } },
});
